# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from apps.common.grpc import common_pb2 as apps_dot_common_dot_grpc_dot_common__pb2


class DataCreateControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/core.common.DataCreateController/Create',
                request_serializer=apps_dot_common_dot_grpc_dot_common__pb2.DataRequest.SerializeToString,
                response_deserializer=apps_dot_common_dot_grpc_dot_common__pb2.DataResponse.FromString,
                )


class DataCreateControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataCreateControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=apps_dot_common_dot_grpc_dot_common__pb2.DataRequest.FromString,
                    response_serializer=apps_dot_common_dot_grpc_dot_common__pb2.DataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.common.DataCreateController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataCreateController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.common.DataCreateController/Create',
            apps_dot_common_dot_grpc_dot_common__pb2.DataRequest.SerializeToString,
            apps_dot_common_dot_grpc_dot_common__pb2.DataResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DataListControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/core.common.DataListController/List',
                request_serializer=apps_dot_common_dot_grpc_dot_common__pb2.DataListRequest.SerializeToString,
                response_deserializer=apps_dot_common_dot_grpc_dot_common__pb2.DataListResponse.FromString,
                )


class DataListControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataListControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=apps_dot_common_dot_grpc_dot_common__pb2.DataListRequest.FromString,
                    response_serializer=apps_dot_common_dot_grpc_dot_common__pb2.DataListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.common.DataListController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataListController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/core.common.DataListController/List',
            apps_dot_common_dot_grpc_dot_common__pb2.DataListRequest.SerializeToString,
            apps_dot_common_dot_grpc_dot_common__pb2.DataListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
